import React, { useCallback } from "react";
import { BsArrowLeftSquare, BsChevronDown, BsDownload } from "react-icons/bs";
import { useRouter } from "next/router";
import useImage from "@/hooks/useImage";
import Head from "next/head";
import FavoriteButton from "@/components/FavoriteButton";
import useInfoModalStore from "@/hooks/useInfoModalStore";
import InfoModal from "@/components/InfoModal";
import DetailesModal from "@/components/DetailesModal";
import useDetailesModalStore from "@/hooks/useDetailesModalStore";

const Watch = () => {
	const router = useRouter();
	const { imageId } = router.query;

	const { data } = useImage(imageId as string);

	const handleDownload = () => {
		const link = document.createElement("a");
		link.href = data?.imageUrl;
		link.download = `${data?.title}.jpg`;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);
	};
	
	const { isOpen, closeModal } = useDetailesModalStore();
	const { openModal } = useDetailesModalStore();
	

	return (
		<>
			<Head>
				<title>{data?.title}</title>
				<meta name="description" content="Generated by Vitae" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<DetailesModal visible={isOpen} onClose={closeModal} />
			<div className="h-screen w-screen bg-black flex flex-column items-center justify-center">
				<nav className="fixed top-0 right-0 left-0 w-full p-4 z-10 flex flex-row items-center gap-8 bg-black bg-opacity-70">
					<BsArrowLeftSquare
						onClick={() => router.push("/")}
						className="w-4 h-8 md:w-10 text-white cursor-pointer hover:opacity-80 transition"
					/>
					<p className="text-white text-1xl md:text-3xl font-bold">
						<span className="text-sky-600">Title:</span> {data?.title}
					</p>
				</nav>

				<img
					className="lg:h-full w-full cursor-all-scroll md:h-auto"
					src={data?.imageUrl}
					alt=""
				/>
				<nav className="fixed bottom-0 right-0 left-0 w-full p-4 z-10 flex flex-row items-center gap-8 bg-black bg-opacity-70">
					<BsDownload
						onClick={handleDownload}
						className="w-4 h-8 md:w-10 text-white cursor-pointer hover:opacity-80 transition absolute right-9 text-sky-600"
					/>

					<FavoriteButton imageId={data?.id} />

					<BsChevronDown
						onClick={() => openModal(data?.id)}
						className="w-4 h-8 md:w-10 text-white cursor-pointer hover:opacity-80 transition"
					/>
				</nav>
			</div>
		</>
	);
};

export default Watch;
