import Input from "@/components/input";
import { useCallback, useState } from "react";
import axios from "axios";
import { signIn } from "next-auth/react";
import Head from "next/head";

const Auth = () => {
	const [email, setEmail] = useState("");
	const [name, setName] = useState("");
	const [password, setPassword] = useState("");

	const [variant, setVariant] = useState("login");

	const toggleVariant = useCallback(() => {
		setVariant((currentVariant) =>
			currentVariant === "login" ? "register" : "login"
		);
	}, []);

	const login = useCallback(async () => {
		
		try {
			await signIn("credentials", {
				email,
				password,
			
				callbackUrl: "/profiles",
			});
		} catch (error) {
			console.log(error);
		}
	}, [email, password]);

	const register = useCallback(async () => {
		try {
			await axios.post("/api/register", {
				email,
				name,
				password,
			});
			login();
		} catch (error) {
			console.log(error);
		}
	}, [email, name, password, login]);

	return (
		<>
			<Head>
				<title>{variant === 'login' ? 'Login' : 'Register'}</title>
				<meta name="description" content="Generated by Vitae" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="relative h-full w-full bg-[url('../public/images/hero.jpg')] bg-no-repeat bg-center bg-fixed bg-cover">
				<div className="bg-black w-full h-full lg:bg-opacity-50">
					<nav className="px-12 py-9 ">
						<img src="../images/logo.svg" alt="Logo" className="h-8 " />
					</nav>
					<div className="flex justify-center">
						<div className="bg-black bg-opacity-70 px-16 py-16 self-center mt-2 lg:w-2/5 lg:max-w-md rounded-md w-full">
							<h2 className="text-white text-4xl mb-8 font-semibold">
								{variant === "login" ? "Sign In" : "Register"}
							</h2>
							<div className="flex flex-col gap-4">
								{variant === "register" && (
									<Input
										id="name"
										label="Name"
										onChange={(e: any) => {
											setName(e.target.value);
										}}
										type="text"
										value={name}
									/>
								)}

								<Input
									id="email"
									label="Email"
									onChange={(e: any) => {
										setEmail(e.target.value);
									}}
									type="email"
									value={email}
								/>

								<Input
									id="password"
									label="Password"
									onChange={(e: any) => {
										setPassword(e.target.value);
									}}
									type="password"
									value={password}
								/>
							</div>
							<button
								onClick={variant === "login" ? login : register}
								className="
                                            bg-sky-500
                                            py-3 
                                            text-white 
                                            rounded-md 
                                            w-full
                                            mt-10
                                            hover:bg-sky-300 
                                            transition

                                            "
							>
								{variant === "login" ? "Login" : "Sign up"}
							</button>
							

							<p className="text-neutral-500 mt-12">
								{variant === "login"
									? "New to Vitae?"
									: "Already have an account?"}

								<span
									onClick={toggleVariant}
									className="text-white ml-1 hover:underline cursor-pointer"
								>
									{variant === "login" ? "Create an account" : "Login"}
								</span>
							</p>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default Auth;
