import Head from "next/head";
import { getSession } from "next-auth/react";
import { NextPageContext } from "next";
import Navbar from "@/components/Navbar";
import Billboard from "@/components/Billboard";
import useInfoModalStore from "@/hooks/useInfoModalStore";
import InfoModal from "@/components/InfoModal";
import ImageList from "@/components/ImageList";
import useImageList from "@/hooks/useImageList";

export async function getServerSideProps(context: NextPageContext) {
	const session = await getSession(context);

	if (!session) {
		return {
			redirect: {
				destination: "/auth",
				permanent: false,
			},
		};
	}
	return {
		props: {},
	};
}

export default function Home() {
	const { data: images = [] } = useImageList();
	const { isOpen, closeModal } = useInfoModalStore();
	return (
		<>
			<InfoModal visible={isOpen} onClose={closeModal} />
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Billboard />
			<div className="pb-40">
				<ImageList title="Trending Now" data={images} />
			</div>
		</>
	);
}
