import ImageCard from "@/components/ImageCard";
import InfoModal from "@/components/InfoModal";
import TypingTitle from "@/components/TypingTitle";
import useImageList from "@/hooks/useImageList";
import useInfoModalStore from "@/hooks/useInfoModalStore";

import Head from "next/head";
import React, { useEffect, useMemo, useState } from "react";

const Search = () => {
	const { data: images = [] } = useImageList();
	const { isOpen, closeModal } = useInfoModalStore();
	let [searchIsNone, setSearchIsNone] = useState(false);
	
	const [searchText, setSearchText] = useState("");
	const searchedImages = useMemo(() => {
		
		return images.filter(
			(e: any) =>
				e.title.toLowerCase().includes(searchText.toLowerCase()) ||
				e.description.toLowerCase().includes(searchText.toLowerCase())
		);
	}, [searchText, images]);

	useEffect(() => {
        
		if (searchedImages.length === 0) {
			setSearchIsNone(true);
		} else {
			setSearchIsNone(false);
		}
	}, [ searchedImages.length ,searchIsNone]);

	return (
		<>
			<Head>
				<title>Search</title>
				<meta name="description" content="Generated by Vitae" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<InfoModal visible={isOpen} onClose={closeModal} />
			<div className="w-full min-h-[100vh] max-w-[1200px] my-0 mx-auto px-5 py-20 ">
				<h1 className="text-4xl text-white font-bold">Search</h1>
				<div className="w-full flex flex-col items-start">
				

					<input
						type="text"
						placeholder="Enter search term . . ."
						className={`w-full bg-transparent transition linear duration-400  shadow-[0_0_2px_#8a8a8a] text-neutral-400 lg:text-xl outline-none my-20 px-3 py-5 rounded-md focus:shadow-lg  focus:shadow-zinc-800 focus:transition`}
						value={searchText}
						onChange={(e) => setSearchText(e.target.value)}
					/>

					{!searchIsNone ? (
						<div className="w-full grid  lg:grid-cols-3 gap-2">
							{searchedImages.map((image:any) => (
								<ImageCard data={image} key={image.id} />
							))}
						</div>
					) : (
						<div className="w-full  flex flex-col items-center">
							<img
								src="/images/profile-blue.png"
								className="w-40 h-40 rounded"
								alt=""
							/>
							<h1 className="lg:text-3xl  text-sky-700 p-10 font-bold  text-xl">
								The Image Not Found
							</h1>
						</div>
					)}
				</div>
			</div>
		</>
	);
};

export default Search;
