import React from "react";
import { getSession } from "next-auth/react";
import { NextPageContext } from "next";
import Head from "next/head";
import useCurrentUser from "@/hooks/useCurrentUser";
import Link from "next/link";

export async function getServerSideProps(context: NextPageContext) {
	const session = await getSession(context);

	if (!session) {
		return {
			redirect: {
				destination: "/auth",
				permanent: false,
			},
		};
	}
	return {
		props: {},
	};
}

const Settings = () => {
	const { data: userData } = useCurrentUser();

	const getEmailVerifiedString = () => {
		if (!userData?.emailVerified) {
			return "Not verified";
		}else{
            return "Verified"
        }
	};

	const createdAtDate = new Date(userData?.createdAt);
console.dir(userData?.favoriteIds.length);
	return (
		<>
			<Head>
				<title>Settings</title>
				<meta name="description" content="Generated by Vitae" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className=" w-full flex py-20 h-full justify-center bg-black ">
				<div className="w-[80vw] flex flex-col">
					<h1 className="text-4xl text-white font-bold">Settings</h1>
					<hr className="my-10" />
					<p className="text-2xl text-white mb-3">
						Name: <span className="text-sky-600">{userData?.name}</span>
					</p>
					<p className="text-2xl text-white mb-3">
						E-Mail: <span className="text-sky-600">{userData?.email}</span>
					</p>
					<p className="text-2xl text-white mb-3">
						ID: <span className="text-sky-600">{userData?.id}</span>
					</p>
					<p className="text-2xl text-white mb-3">
						Email verification status:{" "}
						<span
							className='text-green-600'
						>
							{getEmailVerifiedString()}
						</span>
					</p>
					<p className="text-2xl text-white mb-3">
						Account Was Created At:{" "}
						<span className="text-sky-600">
							{createdAtDate.toLocaleString().slice(0, 10)}
						</span>
					</p>
					<p className="text-2xl text-white mb-3">
						Favorites:{" "}
						<span className="text-sky-600">{userData?.favoriteIds.length}</span>
					</p>
				<Link href="/" className="w-full">
								<button
									className="bg-sky-500
								
                                            py-3
                                            text-white 
                                            rounded-md 
                                            w-full
                                            mt-10
                                            hover:bg-sky-300 
                                            transition"
								>
									Go Back
								</button>
                                </Link>
				</div>
			</div>
		</>
	);
};

export default Settings;
